### ISSUE TITLE
Package conflicting with itself

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/rtree-feedstock#1]
@jakirkham this seems similar to what you are seeing in `hdf5`, correct?

```
TEST START: rtree-0.8.2-py34_0
Fetching package metadata: ........ 
Solving package specifications: . 
Error:  Package missing in current win-32 channels: 
  - rtree 0.8.2 py34_0 
```

**Comment by jakirkham** [comment]
Yeah, it is. Though I do find it a bit strange that in your case, only some environments have this problems and others don't it. Would be really good to figure out why that is.

**Comment by ocefpaf** [comment]
Should be solved now: http://anaconda.org/conda-forge/rtree/files
